# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.175
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.feature_details import FeatureDetails  # noqa: E501
from yapily.rest import ApiException


class TestFeatureDetails(unittest.TestCase):
    """FeatureDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureDetails(self):
        """Test FeatureDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.feature_details.FeatureDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
