"""
    Yapily API

    The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.  # noqa: E501

    The version of the OpenAPI document: 2.13.1
    Contact: support@yapily.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yapily
from yapily.model.amount import Amount
globals()['Amount'] = Amount
from yapily.model.funds_confirmation_request import FundsConfirmationRequest


class TestFundsConfirmationRequest(unittest.TestCase):
    """FundsConfirmationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFundsConfirmationRequest(self):
        """Test FundsConfirmationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FundsConfirmationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
