# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your Application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.49
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.api_response_of_payment_response import ApiResponseOfPaymentResponse  # noqa: E501
from yapily.rest import ApiException


class TestApiResponseOfPaymentResponse(unittest.TestCase):
    """ApiResponseOfPaymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiResponseOfPaymentResponse(self):
        """Test ApiResponseOfPaymentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.api_response_of_payment_response.ApiResponseOfPaymentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
