# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.128
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.user_delete_request import UserDeleteRequest  # noqa: E501
from yapily.rest import ApiException


class TestUserDeleteRequest(unittest.TestCase):
    """UserDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDeleteRequest(self):
        """Test UserDeleteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.user_delete_request.UserDeleteRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
