# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your Application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.107
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.client_based_api_list_response_of_transaction import ClientBasedApiListResponseOfTransaction  # noqa: E501
from yapily.rest import ApiException


class TestClientBasedApiListResponseOfTransaction(unittest.TestCase):
    """ClientBasedApiListResponseOfTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientBasedApiListResponseOfTransaction(self):
        """Test ClientBasedApiListResponseOfTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.client_based_api_list_response_of_transaction.ClientBasedApiListResponseOfTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
