# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.169
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.api_list_response_of_account import ApiListResponseOfAccount  # noqa: E501
from yapily.rest import ApiException


class TestApiListResponseOfAccount(unittest.TestCase):
    """ApiListResponseOfAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiListResponseOfAccount(self):
        """Test ApiListResponseOfAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.api_list_response_of_account.ApiListResponseOfAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
