# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.183
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.site import Site  # noqa: E501
from yapily.rest import ApiException


class TestSite(unittest.TestCase):
    """Site unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSite(self):
        """Test Site"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.site.Site()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
