# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.145
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.inline_response2001_other_accessibility import InlineResponse2001OtherAccessibility  # noqa: E501
from yapily.rest import ApiException


class TestInlineResponse2001OtherAccessibility(unittest.TestCase):
    """InlineResponse2001OtherAccessibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001OtherAccessibility(self):
        """Test InlineResponse2001OtherAccessibility"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.inline_response2001_other_accessibility.InlineResponse2001OtherAccessibility()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
