# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.138
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.inline_response2001_other_atm_services import InlineResponse2001OtherATMServices  # noqa: E501
from yapily.rest import ApiException


class TestInlineResponse2001OtherATMServices(unittest.TestCase):
    """InlineResponse2001OtherATMServices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001OtherATMServices(self):
        """Test InlineResponse2001OtherATMServices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.inline_response2001_other_atm_services.InlineResponse2001OtherATMServices()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
