# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.184
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.overdraft import Overdraft  # noqa: E501
from yapily.rest import ApiException


class TestOverdraft(unittest.TestCase):
    """Overdraft unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOverdraft(self):
        """Test Overdraft"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.overdraft.Overdraft()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
