# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.167
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.geo_location1 import GeoLocation1  # noqa: E501
from yapily.rest import ApiException


class TestGeoLocation1(unittest.TestCase):
    """GeoLocation1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoLocation1(self):
        """Test GeoLocation1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.geo_location1.GeoLocation1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
