"""
    Yapily API

    The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: support@yapily.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yapily
from yapily.model.country import Country
from yapily.model.credentials_type import CredentialsType
from yapily.model.environment_type import EnvironmentType
from yapily.model.feature_enum import FeatureEnum
from yapily.model.media import Media
from yapily.model.monitoring_feature_status import MonitoringFeatureStatus
globals()['Country'] = Country
globals()['CredentialsType'] = CredentialsType
globals()['EnvironmentType'] = EnvironmentType
globals()['FeatureEnum'] = FeatureEnum
globals()['Media'] = Media
globals()['MonitoringFeatureStatus'] = MonitoringFeatureStatus
from yapily.model.institution import Institution


class TestInstitution(unittest.TestCase):
    """Institution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitution(self):
        """Test Institution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Institution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
