# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.159
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.api_list_response_of_consent import ApiListResponseOfConsent  # noqa: E501
from yapily.rest import ApiException


class TestApiListResponseOfConsent(unittest.TestCase):
    """ApiListResponseOfConsent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiListResponseOfConsent(self):
        """Test ApiListResponseOfConsent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.api_list_response_of_consent.ApiListResponseOfConsent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
