"""
    Yapily API

    The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.  # noqa: E501

    The version of the OpenAPI document: 2.13.1
    Contact: support@yapily.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import yapily
from yapily.api.virtual_accounts_api import VirtualAccountsApi  # noqa: E501


class TestVirtualAccountsApi(unittest.TestCase):
    """VirtualAccountsApi unit test stubs"""

    def setUp(self):
        self.api = VirtualAccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_virtual_account(self):
        """Test case for create_virtual_account

        Create Account  # noqa: E501
        """
        pass

    def test_create_virtual_account_beneficiary(self):
        """Test case for create_virtual_account_beneficiary

        Create Beneficiary  # noqa: E501
        """
        pass

    def test_create_virtual_account_client(self):
        """Test case for create_virtual_account_client

        Create Virtual Account Client  # noqa: E501
        """
        pass

    def test_create_virtual_account_pay_out(self):
        """Test case for create_virtual_account_pay_out

        Create Pay Out  # noqa: E501
        """
        pass

    def test_create_virtual_account_transfer(self):
        """Test case for create_virtual_account_transfer

        Create Virtual Account Transfer  # noqa: E501
        """
        pass

    def test_get_pay_in_details(self):
        """Test case for get_pay_in_details

        Get Pay-In Details  # noqa: E501
        """
        pass

    def test_get_payments_by_id(self):
        """Test case for get_payments_by_id

        Get Payment  # noqa: E501
        """
        pass

    def test_get_virtual_account_beneficiaries(self):
        """Test case for get_virtual_account_beneficiaries

        Get List Of Beneficiaries  # noqa: E501
        """
        pass

    def test_get_virtual_account_beneficiary(self):
        """Test case for get_virtual_account_beneficiary

        Get Beneficiary  # noqa: E501
        """
        pass

    def test_get_virtual_account_by_id(self):
        """Test case for get_virtual_account_by_id

        Get Account  # noqa: E501
        """
        pass

    def test_get_virtual_account_clients(self):
        """Test case for get_virtual_account_clients

        Get List of Virtual Account Clients  # noqa: E501
        """
        pass

    def test_get_virtual_account_payments(self):
        """Test case for get_virtual_account_payments

        Get Payments  # noqa: E501
        """
        pass

    def test_get_virtual_accounts(self):
        """Test case for get_virtual_accounts

        Get Accounts  # noqa: E501
        """
        pass

    def test_update_virtual_account_by_id(self):
        """Test case for update_virtual_account_by_id

        Update Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
