# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.127
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.api_list_response_of_feature_details import ApiListResponseOfFeatureDetails  # noqa: E501
from yapily.rest import ApiException


class TestApiListResponseOfFeatureDetails(unittest.TestCase):
    """ApiListResponseOfFeatureDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiListResponseOfFeatureDetails(self):
        """Test ApiListResponseOfFeatureDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.api_list_response_of_feature_details.ApiListResponseOfFeatureDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
