# coding: utf-8

"""
    Yapily API

    To access endpoints that require authentication, use your Application key and secret created in the Dashboard (https://dashboard.yapily.com)  # noqa: E501

    OpenAPI spec version: 0.0.77
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yapily
from yapily.models.response_meta import ResponseMeta  # noqa: E501
from yapily.rest import ApiException


class TestResponseMeta(unittest.TestCase):
    """ResponseMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseMeta(self):
        """Test ResponseMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yapily.models.response_meta.ResponseMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
